### ISSUE TITLE
1.x: verify if async result sanner operations realy need to be synchronized on table object

### ISSUE THREAD

**Issue by mwalkiewicz** [Unoperate/java-bigtable-hbase-1#124]
We should look into implementations of hbase 1.x (and maybe 2.x) and bigtable-java to verify if it is safe to use a single `Table` object and a `ResultScanner` object created using that table in separate threads without synchronization. If the scanner internally uses its parent table, then I think that we can say that it is not safe at all. We should find and report exact places in code where such usages occur.

**Comment by prawilny** [comment]
I claim that neither Bigtable nor HBase (both 1.4.12 and 2.2.3) have any reference to *synchronous* `Table` in their implementations of `ResultScanner`. They only sometimes reference `Connection` or `TableName` but never `Table` object.

HBase 2.x's `AsyncTableResultScanner` has reference to `AsyncTable` but it's thread-safe (and only used to call `getName()`), so we don't have to worry about it.
